[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Viade is a proyect that consists of a decentralized routes management system developed following solid specifications.

* Allow users to share information like pictures or videos about routes with the world at any time.
** The system will be decentralized. Data storage is separated from the app.
** Based on the React framework.
* Main quality goals are usability and maintainability. They will be described in a more detailed way in the next chapter.
* Teachers of Software Architecture and developers will be the stakeholders.

****

==== Developers: 

* Pablo Cañal Suárez. 
* Carmen Vigo Rodríguez.
* Miguel Cuesta Martínez.
* Lucía Megido García.
* Elena Rodríguez Río.

=== Requirements Overview

[role="arc42help"]
****
.Contents
The main requirements are:

* The system will be based on a decentralized architecture where data storage is separated from the app.
* Users can store their routes in their own pods.
* Users can view the routes stored on a map.
* The app will allow a user to share pictures, videos or information about a route with other friends.
* A user can get notifications when some friend shares a route with him.
* Users can have groups of friends with whom they may want to share a route
* It should be possible to view routes loaded by users that are using a different app, so interoperability with other route management systems should be taken into account.

.Motivation
The objective of Viade is to give users a platform where they can share their taste and opinions about the routes they take.
****

=== Quality Goals

[options="header",cols="1,2"]
|===
|Goal|Description
| Usability | All users must be able to use the application with no difficulties. Therefore, the app will be intuitive and will have a user-friendly interface.
| Performance | The service should run fluidly, with no problems or restrictions that affect to its performance efficiency. 
| Availability | The app should always work whevener the user has Internet connection and the server is available.
| Security | User data must be safe. Communications with other devices or users, if done, must be secure.
|===


=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _<Role-1>_ | _<Contact-1>_ | _<Expectation-1>_
| _<Role-2>_ | _<Contact-2>_ | _<Expectation-2>_
|===
