[[section-solution-strategy]]
== Solution Strategy

=== Technology Decisions

Viade will be developed with Solid, the innovative platform that allows the creation of decentralized applications by using Secure Pods, so the privacy of its users is always respected.

As the Solid API is fully written in JavaScript we have decided to do the same and implement our application in the same programming language, for it is the best option for the framework we have chosen as well. 

We will be working with the React framework, which makes it easier to develop interactive and attractive graphic interfaces, which is key to obtain the usable interface we are looking for.

We have decided to run the application in a Node.js environment because of the many tools and modules that provides to developers, it executes code faster than any other language and increases the efficiency of the development process, and much more reasons.

We have not decided yet which testing tool we will be using for testing our project, but we are going to do it because it is a simple way of making sure everything is correct.

We are using Travis for having our project correctly integrated.


=== Design and Architectural Decisions

Top-level-wise, our architecture will be based on the Model-View-Controller (MVC) architectural pattern. This comes as no surprise as the use of React framework heavily relies on this pattern to work. The roles the technologies fill are:

* Pods contain the data about each user, and compose the Model.

* React encapsulates the View aspect of ViaDe.

* The main code will be developed in JavaScript, and deployed on node.js. It fills the Controller role.

In a more realistic deploy of the application, the use of the Broker patter could be interesting to redirect services, but on this scale it is unnecessary.


=== Quality Goals

decisions on on how to achieve key quality goals


=== Organizational Decisions

We have agreed that we will be rotating the charge of writing the minutes, so after each reunion the responsible of sumarizing what we have discussed is a different member.

As all of us have little knowledge about Solid and React, we have decided that all members will do research on both topics and share the links we find interesting through a decidated issue.

.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
