[[section-design-decisions]]
== Design Decisions


****
[width="%"]
|=======
|Decisions |Advantages |Disadvantages
|JavaScript |Provides more resources in Solid. |Not a programming language we are used to.
|Solid | |The scarce sources of documentation.
|React |Efficient update and render of the UI.| Library of a language we are not used to (JavaScript)
|Testing | | 
|Github | | 
|=======
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section , where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****
